# Learn NumPy Fundamentals (Python Library for Data Science)

[This is the link to the course](https://www.udemy.com/course/python-numpy-fundamentals/)

## Index of contents

* [Lesson 1](#lesson_1)
* [Lesson 2](#lesson_2)
* [Lesson 3](#lesson_3)
* [Lesson 4](#lesson_4)
* [Lesson 5](#lesson_5)

<a id='lesson_1'></a>
**Lesson 1**

In [2]:
# This is the standard way to import numpy module
import numpy as np

In [3]:
# Numpy arrays are homogeneous
array_a = np.array([1,2,3,4,5]) # Operations using numpy array are much faster than std python lists.
print(array_a)

[1 2 3 4 5]


In [4]:
# Python built-in list are heterogeneous arrays
print([1,True,3.5,4,'Hello'])

[1, True, 3.5, 4, 'Hello']


In [5]:
# Numpy arrays are dimensional. This operation returns tuple with #rows and #columns
print(array_a.shape)

(5,)


In [6]:
# Two dimensional array of size 5
array_b = np.array([[1, 2, 3, 4, 5],[1, 2, 3, 4, 5]])
print(array_b)
print(array_b.shape)

[[1 2 3 4 5]
 [1 2 3 4 5]]
(2, 5)


In [7]:
# Returns #rows * #cols
print(array_b.size)

10


<a id='lesson_2'></a>
**Lesson 2**

In [9]:
# 3x3
seq_a = [1, 2, 3]
seq_b = [4, 5, 6]
seq_c = ['7', 8, 9]  # String has the highest order of precedence
seq_d = [10.5, 11, 12]  # Float has higher order than integer

In [10]:
# Array always transforms to higher order of precedence.
array_abc = np.array([seq_a, seq_b, seq_c, seq_d])
print(array_abc)
print(array_abc.shape)

[['1' '2' '3']
 ['4' '5' '6']
 ['7' '8' '9']
 ['10.5' '11' '12']]
(4, 3)


In [11]:
a = [True, True, True]
array_a = np.array(a)
print(array_a)

[ True  True  True]


In [12]:
# Boolean has lower level of precedence than integer. Then F=0 and T=1
b = [False, True, 8]
array_b = np.array(b)
print(array_b)

[0 1 8]


<a id='lesson_3'></a>
**Lesson 3**

In [13]:
array_a = np.array([[1, 2, 3],[4, 5, 6]])
print(array_a.shape)
print(array_a.size)

(2, 3)
6


In [14]:
# Reshape method does not overwrite original array, only returns a copy of the new shape.
array_b = array_a.reshape(3, 2)  # New shape need to be on same size as original.
print(array_b)

[[1 2]
 [3 4]
 [5 6]]


In [15]:
# Transpose will reshape exchanging #row by #col and grouping elements different than a manual reshape.
array_c = array_a.T
print(array_c)

[[1 4]
 [2 5]
 [3 6]]


In [16]:
# Returns of the array
print(array_c[:])
# Returns all rows and columns. THIS IS DIFFERENT THAN PYTHON LIST.
print(array_c[:, :])
# Returns all rows but only column 2 (Only column 2 in other words)
print(array_c[:, 1])

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]
[4 5 6]


_**Practice**_

In [17]:
array_a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(array_a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [18]:
array_b = array_a.reshape(2, 8)
print(array_b)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [19]:
array_c = array_a.T
print(array_c)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [20]:
# To print only the two columns in the middle
print(array_c[:, 1:3])

[[ 5  9]
 [ 6 10]
 [ 7 11]
 [ 8 12]]


In [21]:
# To print only the two rows in the middle
print(array_c[1:3, :])

[[ 2  6 10 14]
 [ 3  7 11 15]]


In [22]:
# From the second column starting at the end, return the second element in the column
print(array_c[:, -2][1])

10


<a id='lesson_4'></a>
**Lesson 4**

In [23]:
# The dtype argument allows to specify the data type of the array
array_a = np.array([[1,2,3],[4,5,6]], dtype=float)
print(array_a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [26]:
# This method creates array of 0s of given shape
array_b = np.zeros((3,3))
print(array_b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [27]:
# This method creates array of 1s of given shape
array_c = np.ones((3,3))
print(array_c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [28]:
# This method allows to create array of a specific item. First argument is shape, second is the data.
array_d = np.full((3,3), True)
print(array_d)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [33]:
# Creates random array of integers between first arguments, of shape third argument
array_e = np.random.randint(-50, 50, (3, 3))
print(array_e)

[[-34  45 -24]
 [ 21  17 -50]
 [-34 -47  45]]


In [35]:
# Created random floats between 0 and 1. Only takes shape as argument.
array_f = np.random.random([3,3])
print(array_f)

[[0.15257217 0.56168217 0.91572999]
 [0.82057515 0.39695502 0.91472653]
 [0.51887161 0.9226915  0.45646453]]


**_Practice_**

In [36]:
# The third number will cause an overflow.
array_a = np.array([32766, 32767, 32768], dtype=np.int16)
# To print data type of a numpy array
print(array_a.dtype)

int16


C:\Users\cm-desktop\AppData\Local\Temp\ipykernel_26276\2736945649.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 32768 to int16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array_a = np.array([32766, 32767, 32768], dtype=np.int16)


In [37]:
# This will lead to an overflow because the data type is unsigned
array_b = np.array([[-1, 0, 1]], dtype=np.uint16)
print(array_b)

[[65535     0     1]]


C:\Users\cm-desktop\AppData\Local\Temp\ipykernel_26276\2377430693.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -1 to uint16 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  array_b = np.array([[-1, 0, 1]], dtype=np.uint16)
